### ISSUE TITLE
Invalid license?

### ISSUE THREAD

**Issue by akx** [nsdnwe/R-kielen-perusteet#2]
The LICENSE file claims this repo's copyright belongs to Ali Al Dallal, 2015. Is this correct?

https://github.com/nsdnwe/R-kielen-perusteet/blob/0746b32c69cfc704300b5713d59c04c530d2688f/LICENSE#L3

**Comment by nsdnwe** [comment]
That's incorrect. Copy-paste fail. Now fixed.
